### ISSUE TITLE
Vendored copy of ScaLAPACK does not build with GCC 14

### ISSUE THREAD

**Issue by prckent** [RMGDFT/rmgdft#94]
FYI, unfortunately the vendored copy of ScaLAPACK that is included with rmg does not work with (at least) GCC 14.2.0 due to a bad declaration and the improved (in)consistency checking.  This has been noticed elsewhere by other people building/using ScaLAPACK. GCC 12.2.0 appears OK. Other than using an older compiler, can you suggest a workaround? I am building via spack and was hoping to achieve a set of pure GCC 14 builds for various electronic structure packages.  One non-ideal possibility would be a local patch (not sure how extensive this needs to be), or to mark the package as incompatible with GCC 14 in spack.

Thanks, Paul

```
     1143    /scratch/pk7/spack_build_stage/spack-stage-rmgdft-6.1.0-b6apu5imwytero2v7whsjdbry4raa6jb/spack-src/scalapack/BLACS/SRC/igsum2d_.c: In function 'igsum2d_':
  >> 1144    /scratch/pk7/spack_build_stage/spack-stage-rmgdft-6.1.0-b6apu5imwytero2v7whsjdbry4raa6jb/spack-src/scalapack/BLACS/SRC/igsum2d_.c:154:7: error: implicit declaration of function 'BI_imvcopy'; did yo
             u mean 'BI_zmvcopy'? [-Wimplicit-function-declaration]
     1145      154 |       BI_imvcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
     1146          |       ^~~~~~~~~~
     1147          |       BI_zmvcopy
  >> 1148    /scratch/pk7/spack_build_stage/spack-stage-rmgdft-6.1.0-b6apu5imwytero2v7whsjdbry4raa6jb/spack-src/scalapack/BLACS/SRC/igsum2d_.c:169:13: error: implicit declaration of function 'BI_ivmcopy'; did y
             ou mean 'BI_cvmcopy'? [-Wimplicit-function-declaration]
     1149      169 |             BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
     1150          |             ^~~~~~~~~~
     1151          |             BI_cvmcopy
     1152    /scratch/pk7/spack_build_stage/spack-stage-rmgdft-6.1.0-b6apu5imwytero2v7whsjdbry4raa6jb/spack-src/scalapack/BLACS/SRC/igsum2d_.c:82:45: warning: unused variable 'itr' [-Wunused-variable]
     1153       82 |    Int N, length, dest, tlda, trdest, ierr, itr;
     1154          |                                             ^~~
     1155    /scratch/pk7/spack_build_stage/spack-stage-rmgdft-6.1.0-b6apu5imwytero2v7whsjdbry4raa6jb/spack-src/scalapack/BLACS/SRC/igsum2d_.c:82:39: warning: variable 'ierr' set but not used [-Wunused-but-set-
             variable]
     1156       82 |    Int N, length, dest, tlda, trdest, ierr, itr;
     1157          |                                       ^~~~
```

**Comment by elbriggs** [comment]
I'm looking into possible solutions. If a local patch is not super extensive I would prefer going with that rather than marking it as incompatible with gcc 14 but don't know enough to say just yet.

**Comment by prckent** [comment]
Thanks Emil.

**Comment by prckent** [comment]
Checking on the status of this. Is there a workaround?

**Comment by elbriggs** [comment]
I just tried building scalapack using the latest v 2.2.2 release and unfortunately the issue is still not fixed. The errors are restricted to 4 files and I am looking into the feasibility of modifying these in the included version so that compilation with GCC >14 works.

**Comment by elbriggs** [comment]
I have gotten scalapack v2.2.2 to build with gcc14 but I need to do further testing to confirm everything works as expected. There will also be some config magic needed to ensure things work with other compilers.

**Comment by prckent** [comment]
Provided the fixes are "only" for the removal of illegal Fortran I would hope that no additional config magic is needed since this tends to be very brittle...

**Comment by elbriggs** [comment]
So it appears the only additional config magic required is to force the use of the C90 standard for the BLACS portion of scalapack. When I build a standalone scalapack like this using gcc 14 it passes all the internal scalapack tests. When built as part of RMG it passes all of our tests. 

I suppose it's possible that a future revision of scalapack will require C99 but that's not a problem for us as we are including a specific version.

**Comment by elbriggs** [comment]
Also confirmed that it builds and runs correctly using gcc 13 so I have committed the updated code to develop.
